### PR TITLE
Fetch only last hour of sensor data

### LINKED ISSUE #1: Updating lacrosseview sensor took longer than the scheduled update interval 0:00:30
First, thanks for this integration, I wanted to look into writing this myself, but you were faster :-).

Now back to my issue: The hass log is filled with:

```
Updating lacrosseview sensor took longer than the scheduled update interval 0:00:30
```

The problem is that fetching whole history of sensor data takes incredibly long. This can be improved by fetching only the last few entries (the integration anyway only uses the last measurement anyway). So passing `from` while fetching the data heavily improves the performance.

### PR DESCRIPTION
**Pull request by nijel**
This heavily reduces request time (and server load).

Fixes #1

This works for me, but additional testing is welcome.

### CODE REVIEW

**Comment by regulad** [comment]
This could certainly work but have you acknowledged the situation in which a sensor is offline and is unable to report it's state for the past hour?

I believe it may be a bit rickety, but it is certainly possible to have an internal attribute with the type of a `datetime` that is set each time it is polled, and then fetch since this value if it's present, fetching the entire history if it isn't.

This would resolve the above situation, as HA will simply continue to use the last known value or mark it as Unavailable (which would be the desired outcome).

**Comment by nijel** [comment]
How about toggling availability flag accordingly? I just changed the patch in this way.

**Comment by regulad** [comment]
Good enough.

**Comment by regulad** [comment]
Thank you for your work. I will be releasing a new version when and if my LaCrosse view change get merged into the brands repository.

**Pull request merged**
